services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cit_laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: cit_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: livecoding
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password1234
      MYSQL_USER: livecoding
    ports:
      - 3366:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: cit_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cit_phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: livecoding
      PMA_PASSWORD: password1234
    networks:
      - laravel
    depends_on:
      - mysql


volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
